---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stunner.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "stunner.metadata.annotations" . | nindent 4 }}  
spec:
  selector:
    matchLabels:
      {{- include "stunner.labels" . | nindent 6 }}
  replicas: {{ .Values.stunner.deployment.replica }}
  template:
    metadata:
      labels:
        {{- include "stunner.labels" . | nindent 8 }}
    spec:
{{- if eq .Values.stunner.deployment.container.configWatcher.enabled true}}
      serviceAccountName: {{ .Values.stunner.deployment.container.configWatcher.serviceAccountName }}
{{- end }}
      {{- include "stunner.stunnerGatewayOperator.volume" . | indent 6 }}
      terminationGracePeriodSeconds: {{ .Values.stunner.deployment.container.stunnerd.terminationGracePeriodSeconds }}
      hostNetwork: {{ .Values.stunner.deployment.hostNetwork }}
      containers:
      - name: {{ .Values.stunner.deployment.container.stunnerd.name }}
        image: "{{ .Values.stunner.deployment.container.stunnerd.image.repository }}{{ .Values.stunner.deployment.container.stunnerd.image.name }}:{{ .Values.stunner.deployment.container.stunnerd.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.stunner.deployment.container.stunnerd.image.pullPolicy }}
        {{- include "stunner.stunnerGatewayOperator.args" . | indent 8 }}
        resources: {{- toYaml .Values.stunner.deployment.container.stunnerd.resources | nindent 10 }}
        livenessProbe: {{- toYaml .Values.stunner.deployment.container.stunnerd.livenessProbe | nindent 10 }}
        readinessProbe: {{- toYaml .Values.stunner.deployment.container.stunnerd.readinessProbe | nindent 10 }}
{{- if eq .Values.stunner.deployment.monitoring.enabled true}}
        ports:
          - name: {{ .Values.stunner.deployment.monitoring.portName }}
            containerPort: {{ .Values.stunner.deployment.monitoring.containerPort }}
{{- end }}
{{- if eq .Values.stunner.deployment.container.configWatcher.enabled true}}
      - name: config-watcher
        image: kiwigrid/k8s-sidecar:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: stunnerd-config-volume
            mountPath: /etc/stunnerd
        env: {{- toYaml .Values.stunner.deployment.container.configWatcher.env | nindent 8 }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        resources: {{- toYaml .Values.stunner.deployment.container.configWatcher.resources | nindent 10 }}
{{- end}}
{{- if eq .Values.stunner.deployment.container.netdebug.enabled true}}
      - name: net-debug
        image: l7mp/net-debug:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
{{- end}}
      {{- with .Values.stunner.deployment.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stunner.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
---
