apiVersion: v2
name: gateway-api-standard-crds
description: Kubernetes Gateway API Standard channel CRDs
type: application
version: 1.4.1
appVersion: 1.4.1
home: https://github.com/kubernetes-sigs/gateway-api
keywords:
  - gateway-api
  - crd
maintainers:
  - name: l7mp
    email: info@l7mp.io
    url: https://l7mp.io
