name: Test Helm chart installation

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]


jobs:
  test_install:
    runs-on: ubuntu-latest
    steps:
      - name: stunner-helm checkout
        uses: actions/checkout@v6
        with:
          path: stunner-helm
          ref: main
          repository: l7mp/stunner-helm

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Edit charts to use dev images
        run: |
          cd stunner-helm/helm
          yq -i '
            .name = "stunner-gateway-operator-dev" |
            .appVersion = "dev"
          ' stunner-gateway-operator/Chart.yaml
          yq -i '
            .stunnerGatewayOperator.deployment.container.manager.image.pullPolicy = "Always" |
            .stunnerGatewayOperator.deployment.container.manager.image.tag = "dev" |
            .stunnerGatewayOperator.dataplane.spec.image.pullPolicy = "Always" |
            .stunnerGatewayOperator.dataplane.spec.image.tag = "dev" |
            .stunnerAuthService.deployment.container.authService.image.pullPolicy = "Always" |
            .stunnerAuthService.deployment.container.authService.image.tag = "dev"
          ' stunner-gateway-operator/values.yaml

      - name: Test chart installability
        run: |
          cd stunner-helm
          ct install --chart-dirs helm --charts helm/stunner-gateway-operator
