name: Test Helm charts
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches: [ main ]


jobs:
  test_charts:
    runs-on: ubuntu-latest
    steps:
      - name: stunner-helm checkout
        uses: actions/checkout@v3
        with:
          path: stunner-helm
          ref: main
          repository: l7mp/stunner-helm

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: |
          cd stunner-helm
          ct lint --all --chart-dirs helm --excluded-charts stunner-kurento-one2one-call

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
        run: |
          cd stunner-helm
          ct install --all --chart-dirs helm --excluded-charts stunner-kurento-one2one-call
