name: Test Helm charts
on:
  workflow_dispatch:


jobs:
  test_charts:
    runs-on: ubuntu-latest
    steps:
      - name: stunner-helm checkout
        uses: actions/checkout@v3
        with:
          path: stunner-helm
          ref: main
          repository: l7mp/stunner-helm

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (lint and install)
        run: |
          cd stunner-helm
          ct lint-and-install --all --upgrade --chart-dirs helm --excluded-charts stunner-kurento-one2one-call
