name: Test Helm chart upgrade
on:
  workflow_dispatch:
  schedule:
  - cron: '0 11 * * 1'

jobs:
  test_upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.2

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Install charts
        run: |
          helm repo add stunner https://l7mp.io/stunner
          helm repo update
          helm install stunner-gateway-operator stunner/stunner-gateway-operator --create-namespace --namespace=stunner
          helm install stunner stunner/stunner --create-namespace --namespace=stunner

      - name: Upgrade charts
        run: |
          helm upgrade stunner-gateway-operator stunner/stunner-gateway-operator-dev --create-namespace --namespace=stunner
          helm upgrade stunner stunner/stunner-dev --create-namespace --namespace=stunner
